### ISSUE TITLE
Generator cookbooks won't need to be named 'code_generator' in the future

### ISSUE THREAD

**Issue by danielsdeleo** [echohack/pan#1]
Hi,

Thanks for creating this (and writing it up). Just want to let you know I'm working on a change in ChefDK so you won't need to name the cookbook "code_generator" in the future (though of course you can still name it that if you like): https://github.com/opscode/chef-dk/pull/265

Not sure if there's anything for you to actually do here so feel free to close this.

Thanks!

**Comment by echohack** [comment]
Thank you Dan!

I'll fix up the repo for when the changes in the ChefDK go live, so we can provide the most up to date example. Thanks for opening this issue!

**Comment by echohack** [comment]
Done! https://github.com/echohack/pan/commit/77af874fdbf306ef7e51383e19ad60b0974c5ea5
